# сборка
FROM gradle:8.11 AS build
WORKDIR /app
COPY gradlew settings.gradle.kts build.gradle.kts /app/
COPY gradle /app/gradle
COPY frontback /app/frontback
RUN chmod +x gradlew
#RUN ls -a && false
RUN ./gradlew :frontback:clean :frontback:build

# запуск
FROM eclipse-temurin:21-jre
WORKDIR /app
# копируем файл полученный в итоге из AS build
COPY --from=build /app/frontback/build/libs/frontback-all.jar frontback-all.jar
EXPOSE 8080
CMD ["java", "-jar", "frontback-all.jar"]