# Сборка
FROM gradle:8.11 AS build
COPY gradlew .
COPY frontback frontback
COPY gradle gradle
COPY settings.gradle.kts .
COPY build.gradle.kts .
WORKDIR .
RUN chmod +x gradlew
RUN ./gradlew :frontback:clean :frontback:build --stacktrace

# Запуск
FROM eclipse-temurin:21-jre
WORKDIR .
COPY /frontback/build/libs/frontback-all.jar frontback-all.jar
EXPOSE 8080
CMD ["java", "-jar", "frontback-all.jar"]