FROM golang:1.25.5 AS builder
WORKDIR /app
COPY ../auth_service /app/
RUN go mod download
RUN cd main && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o authorization

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main/authorization authorization
EXPOSE 8081
#RUN pwd && ls -a && cd authorization && pwd && ls -a false
RUN chmod +x authorization
CMD ["./authorization"]