FROM golang:1.25.5 AS builder # TODO добить, чет не пашет
WORKDIR /app
COPY ../auth_service /app/
RUN go mod download
RUN cd main && go build -o authorization

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main/authorization authorization
EXPOSE 8081
#RUN pwd && ls -a && false
CMD ["ls"]
CMD ["./authorization"]